const CONSTANT = require('../../utils/serverConstants');

module.exports = {
    userSeedData: [
        {
            email: 'teste1@email.com.br',
            username: 'teste1',
            password: 'just4now'
        },
        {
            email: 'teste2@email.com.br',
            username: 'teste2',
            password: 'just4now'
        },
        {
            email: 'teste3@email.com.br',
            username: 'teste3',
            password: 'just4now'
        },
        {
            email: 'teste4@email.com.br',
            username: 'teste4',
            password: 'just4now'
        },
        {
            email: 'teste5@email.com.br',
            username: 'teste5',
            password: 'just4now'
        }
    ],
    roomSeedData: [
        {
            name: 'Private Room #1',
            password: 'just4now'
        },
        {
            name: 'Private Room #2',
            password: 'just4now'
        },
        {
            name: 'Public Room #1',
            password: ''
        },
        {
            name: 'Public Room #2',
            password: ''
        }
    ],
    messageSeedData: [
        {
            content: 'Test Message 1'
        },
        {
            content: 'Test Message 2'
        },
        {
            content: 'Test Message 3'
        }
    ],
    variantIndicatorSeedData: [
        {
            product_id: 101,
            variant_id: 1011,
            title: 'Tênis Nike Air Max 97 Throwback Future',
            handle: 'Air Max 97 Throwback Future',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'THROWBACK3019BLACK',
            price: 49.99,
            size: '40',
            color: 'Preto',
            material: 'Couro',
            vendor: 'Nike',
            inventory_item_id: 1011,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 10,
            sales_potential_avg: 5,
            sales_volume: 20,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 102,
            variant_id: 1021,
            title: 'Tênis Nike Lebron 16',
            handle: 'Lebron 16',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'LEBRON163019WHITE',
            price: 99.99,
            size: '40',
            color: 'Branco',
            material: 'Couro',
            vendor: 'Nike',
            inventory_item_id: 1021,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 10,
            sales_potential_avg: 5,
            sales_volume: 21,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 103,
            variant_id: 1031,
            title: 'Tênis Nike Air Jordan Proto React',
            handle: 'Air Jordan Proto React',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'AIRJORDAN3019BLACK',
            price: 99.99,
            size: '40',
            color: 'Preto',
            material: 'Couro',
            vendor: 'Nike',
            inventory_item_id: 1031,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 9,
            sales_potential_avg: 5,
            sales_volume: 21,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 102,
            variant_id: 1022,
            title: 'Tênis Nike Lebron 16 Low',
            handle: 'Lebron 16 Low',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'LEBRON16LOW3019BLACK',
            price: 149.99,
            size: '40',
            color: 'Preto',
            material: 'Couro',
            vendor: 'Nike',
            inventory_item_id: 1022,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 9,
            sales_potential_avg: 5,
            sales_volume: 20,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 105,
            variant_id: 1051,
            title: 'Tênis Nike Kyrie 5',
            handle: 'Kyrie 5',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'LEBRON16LOW3019BLACK',
            price: 240.0,
            size: '40',
            color: 'Branco',
            material: 'Couro',
            vendor: 'Nike',
            inventory_item_id: 1051,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 8,
            sales_potential_avg: 5,
            sales_volume: 30,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 106,
            variant_id: 1061,
            title: 'Tênis Adidas Stan Smith',
            handle: 'Stan Smith',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'STANSMITH3019WHITE',
            price: 300.0,
            size: '40',
            color: 'Branco',
            material: 'Couro',
            vendor: 'Adidas',
            inventory_item_id: 61,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 8,
            sales_potential_avg: 5,
            sales_volume: 10,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 107,
            variant_id: 1071,
            title: 'Tênis Adidas Seeley',
            handle: 'Seeley',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'SEELEY3019WHITE',
            price: 300.0,
            size: '40',
            color: 'Branco',
            material: 'Couro',
            inventory_item_id: 71,
            vendor: 'Adidas',
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 7,
            sales_potential_avg: 5,
            sales_volume: 50,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 108,
            variant_id: 1081,
            title: 'Tênis Adidas X_Plr',
            handle: 'X_Plr',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'X_PLR3019BLUE',
            price: 300.0,
            size: '40',
            color: 'Azul',
            material: 'Couro',
            vendor: 'Adidas',
            inventory_item_id: 1081,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 7,
            sales_potential_avg: 5,
            sales_volume: 20,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 109,
            variant_id: 1091,
            title: 'Tênis Adidas Prophere',
            handle: 'Prophere',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'PROPHERE3019WHITE',
            price: 300.0,
            size: '40',
            color: 'Branco',
            material: 'Couro',
            vendor: 'Adidas',
            inventory_item_id: 1091,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 6,
            sales_potential_avg: 5,
            sales_volume: 18,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 110,
            variant_id: 1101,
            title: 'Tênis Adidas Deerupt Runner',
            handle: 'Deerupt Runner',
            product_type_id: 2,
            product_type_title: 'Tênis',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 1,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/tenis_adidas_n-5923_p_reto_masculino_3__1_3e1dd2e7-37cb-4737-b0f9-e2dd4c482e40_200x200@2x.jpg?v=1558342663',
            sku: 'DEERUPTRUNNER3019BLACK',
            price: 300.0,
            size: '40',
            color: 'Preto',
            material: 'Couro',
            vendor: 'Adidas',
            inventory_item_id: 1101,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 6,
            sales_potential_avg: 5,
            sales_volume: 120,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 201,
            variant_id: 2011,
            title: 'Chinelo Vans Slide-on Checkboard 1',
            handle: 'Chinelo Slideon 1',
            product_type_id: 9,
            product_type_title: 'Chinelo',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 2,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/chinelo_vans_slide-on_checkerboard_preto_250x_crop_center.jpg?v=1560455189',
            sku: 'SLIDEON2019BLACK',
            price: 49.99,
            size: '40',
            color: 'Preto',
            material: 'Têxtil',
            vendor: 'Vans',
            inventory_item_id: 2011,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 10,
            sales_potential_avg: 5,
            sales_volume: 10,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 202,
            variant_id: 2021,
            title: 'Chinelo Vans Slide-on Checkboard 2',
            handle: 'Chinelo Slideon 2',
            product_type_id: 9,
            product_type_title: 'Chinelo',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 2,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/chinelo_vans_slide-on_checkerboard_preto_250x_crop_center.jpg?v=1560455189',
            sku: 'SLIDEON2019WHITE',
            price: 99.99,
            size: '40',
            color: 'Branco',
            material: 'Têxtil',
            vendor: 'Vans',
            inventory_item_id: 2021,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 9,
            sales_potential_avg: 5,
            sales_volume: 20,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 203,
            variant_id: 2031,
            title: 'Chinelo Vans Slide-on Checkboard 3',
            handle: 'Chinelo Slideon 3',
            product_type_id: 9,
            product_type_title: 'Chinelo',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 2,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/chinelo_vans_slide-on_checkerboard_preto_250x_crop_center.jpg?v=1560455189',
            sku: 'SLIDEON2019GREEN',
            price: 149.99,
            size: '40',
            color: 'Verde',
            material: 'Têxtil',
            vendor: 'Vans',
            inventory_item_id: 2031,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 5,
            sales_potential_avg: 5,
            sales_volume: 15,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 204,
            variant_id: 2041,
            title: 'Chinelo Vans Slide-on Checkboard 4',
            handle: 'Chinelo Slideon 4',
            product_type_id: 9,
            product_type_title: 'Chinelo',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 2,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/chinelo_vans_slide-on_checkerboard_preto_250x_crop_center.jpg?v=1560455189',
            sku: 'SLIDEON2019RED',
            price: 300.99,
            size: '40',
            color: 'Vermelho',
            material: 'Têxtil',
            vendor: 'Vans',
            inventory_item_id: 2041,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 6,
            sales_potential_avg: 5,
            sales_volume: 5,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 2000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 301,
            variant_id: 3011,
            title: 'Camiseta Kings Bronx 1',
            handle: 'Camiseta Kings Bronx 1',
            product_type_id: 4,
            product_type_title: 'Camiseta',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 3,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/camseta_kings_bronx_cinza_masculina_3_150x150.jpg?v=1560454833',
            sku: 'KINGSBRONX3019BLACK',
            price: 49.99,
            size: 'M',
            color: 'Preto',
            material: 'Malha',
            vendor: 'Kings',
            inventory_item_id: 3011,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 10,
            sales_potential_avg: 5,
            sales_volume: 10,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 302,
            variant_id: 3021,
            title: 'Camiseta Kings Bronx 2',
            handle: 'Camiseta Kings Bronx 2',
            product_type_id: 4,
            product_type_title: 'Camiseta',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 3,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/camseta_kings_bronx_cinza_masculina_3_150x150.jpg?v=1560454833',
            sku: 'KINGSBRONX3019WHITE',
            price: 99.99,
            size: 'M',
            color: 'Branco',
            material: 'Malha',
            vendor: 'Kings',
            inventory_item_id: 3021,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 9,
            sales_potential_avg: 5,
            sales_volume: 30,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 303,
            variant_id: 3031,
            title: 'Camiseta Kings Bronx 3',
            handle: 'Camiseta Kings Bronx 3',
            product_type_id: 4,
            product_type_title: 'Camiseta',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 3,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/camseta_kings_bronx_cinza_masculina_3_150x150.jpg?v=1560454833',
            sku: 'KINGSBRONX3019GREEN',
            price: 149.99,
            size: 'M',
            color: 'Verde',
            material: 'Malha',
            vendor: 'Kings',
            inventory_item_id: 3031,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 6,
            sales_potential_avg: 5,
            sales_volume: 20,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 304,
            variant_id: 3041,
            title: 'Camiseta Kings Bronx 4',
            handle: 'Camiseta Kings Bronx 4',
            product_type_id: 4,
            product_type_title: 'Camiseta',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 3,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/camseta_kings_bronx_cinza_masculina_3_150x150.jpg?v=1560454833',
            sku: 'KINGSBRONX3019RED',
            price: 300.0,
            size: 'M',
            color: 'Vermelho',
            material: 'Malha',
            vendor: 'Kings',
            inventory_item_id: 3041,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 8,
            sales_potential_avg: 5,
            sales_volume: 7,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 401,
            variant_id: 4011,
            title: 'Moletom Nike Jordan Camuflado 1',
            handle: 'Moletom Nike Jordan Camuflado 1',
            product_type_id: 6,
            product_type_title: 'Moletom',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 4,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/moletom_nike_jordan_camuflado_verde_masculino_1_600x_crop_center.jpg?v=1560457697',
            sku: 'MOLETONJORDAN3019BLACK',
            price: 49.99,
            size: 'M',
            color: 'Preto',
            material: '100% Algodão',
            vendor: 'Nike',
            inventory_item_id: 4011,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 7,
            sales_potential_avg: 5,
            sales_volume: 30,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 402,
            variant_id: 4021,
            title: 'Moletom Nike Jordan Camuflado 2',
            handle: 'Moletom Nike Jordan Camuflado 2',
            product_type_id: 6,
            product_type_title: 'Moletom',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 4,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/moletom_nike_jordan_camuflado_verde_masculino_1_600x_crop_center.jpg?v=1560457697',
            sku: 'MOLETONJORDAN3019WHITE',
            price: 99.99,
            size: 'M',
            color: 'Branco',
            material: '100% Algodão',
            vendor: 'Nike',
            inventory_item_id: 4021,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 10,
            sales_potential_avg: 5,
            sales_volume: 10,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 403,
            variant_id: 4031,
            title: 'Moletom Nike Jordan Camuflado 3',
            handle: 'Moletom Nike Jordan Camuflado 3',
            product_type_id: 6,
            product_type_title: 'Moletom',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 4,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/moletom_nike_jordan_camuflado_verde_masculino_1_600x_crop_center.jpg?v=1560457697',
            sku: 'MOLETONJORDAN3019GREEN',
            price: 149.99,
            size: 'M',
            color: 'Verde',
            material: '100% Algodão',
            vendor: 'Nike',
            inventory_item_id: 4031,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 6,
            sales_potential_avg: 5,
            sales_volume: 50,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        },
        {
            product_id: 404,
            variant_id: 4041,
            title: 'Moletom Nike Jordan Camuflado 4',
            handle: 'Moletom Nike Jordan Camuflado 4',
            product_type_id: 6,
            product_type_title: 'Moletom',
            collection_id: 434521,
            collection_title: 'Masculino',
            image_id: 4,
            image_src:
                'https://cdn.shopify.com/s/files/1/0088/1587/0029/products/moletom_nike_jordan_camuflado_verde_masculino_1_600x_crop_center.jpg?v=1560457697',
            sku: 'MOLETONJORDAN3019RED',
            price: 300.0,
            size: 'M',
            color: 'Vermelho',
            material: '100% Algodão',
            vendor: 'Nike',
            inventory_item_id: 4041,
            inventory_quantity: '5',
            inventory_cost: '10.00',
            inventory_optimal: '100',
            sales_potential: 9,
            sales_potential_avg: 5,
            sales_volume: 80,
            sales_volume_avg: 9,
            sales_volume_optimal: 9,
            sales_value: 3000,
            sales_value_avg: 900,
            sales_value_optimal: 900,
            pc1: 1,
            pc1_percentage: 1,
            pc1_potential: 1,
            pc1_potential_percentage: 1,
            pc1_optimal: 1,
            pc1_optimal_percentage: 1
        }
    ],
    productTypeSeedData: [
        {
            id: 1,
            title: 'Boné'
        },
        {
            id: 2,
            title: 'Tênis'
        },
        {
            id: 4,
            title: 'Camiseta'
        },
        {
            id: 5,
            title: 'Regata'
        },
        {
            id: 6,
            title: 'Moletom'
        },
        {
            id: 7,
            title: 'Bermuda'
        },
        {
            id: 8,
            title: 'Shorts'
        },
        {
            id: 9,
            title: 'Chinelo'
        },
        {
            id: 20,
            title: 'Meia'
        },
        {
            id: 11,
            title: 'Calça'
        },
        {
            id: 12,
            title: 'Bolsa'
        },
        {
            id: 13,
            title: 'Jaqueta e Casaco'
        },
        {
            id: 14,
            title: 'Pochete'
        },
        {
            id: 15,
            title: 'Mochila'
        }
    ],
    collectionSeedData: [
        {
            id: 434521,
            title: 'Masculino'
        },
        {
            id: 434522,
            title: 'Feminino'
        },
        {
            id: 434523,
            title: 'Juvenil'
        }
    ],
    priceRangeSeedData: [
        {
            id: 1,
            start_at: 0,
            end_at: 50
        },
        {
            id: 2,
            start_at: 51,
            end_at: 200
        },
        {
            id: 3,
            start_at: 201,
            end_at: 150
        },
        {
            id: 4,
            start_at: 150,
            end_at: parseInt(CONSTANT.PRICE.MAX_RANGE.VALUE)
        }
    ],
    coverageSeedData: [
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 1,
            product_type_title: 'Boné',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 2,
            product_type_title: 'Tênis',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 4,
            product_type_title: 'Camiseta',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 5,
            product_type_title: 'Regata',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 6,
            product_type_title: 'Moletom',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 7,
            product_type_title: 'Bermuda',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 8,
            product_type_title: 'Shorts',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 9,
            product_type_title: 'Chinelo',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 20,
            product_type_title: 'Meia',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 11,
            product_type_title: 'Calça',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 12,
            product_type_title: 'Bolsa',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 13,
            product_type_title: 'Jaqueta e Casaco',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 14,
            product_type_title: 'Pochete',
            coverage_min: 0,
            coverage_optimal: 0
        },
        {
            collection_id: 434521,
            collection_title: 'Masculino',
            product_type_id: 15,
            product_type_title: 'Mochila',
            coverage_min: 0,
            coverage_optimal: 0
        }
    ]
};
