
export const getSampleData = () => {
  return [
      {
        date: '01/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '02/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '03/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '04/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '05/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '06/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '07/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '08/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '09/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      },
      {
        date: '10/10/2019',
        orders_volume: 30,
        orders_volume_delivered: 10,
        orders_percentage_delay: '5%',
        orders_avg_shipping_time: '3 dias',
        orders_avg_shipping_time_delay: '2 dias',
        orders_volume_returned: '1%',
      }
  ]
}
